# Generated by Django 5.0.1 on 2024-01-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_entregable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(upload_to='')),
                ('contenido', models.CharField(max_length=2500)),
            ],
        ),
    ]
