# Generated by Django 5.0.1 on 2024-01-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='subtitulo',
        ),
        migrations.AddField(
            model_name='blog',
            name='codigo',
            field=models.IntegerField(default=111111),
            preserve_default=False,
        ),
    ]
